project:
  type: website

website:
  title: "Dr. Julien P. Irmer"
  navbar:
    logo: assets/me.png
    left:
      - publications.qmd
      - talks.qmd
      - workshops.qmd
      - cv.qmd
    right:
      - href: https://www.linkedin.com/in/jpirmer
        text: <i class="fa-brands fa-linkedin"></i>
      - href: https://www.researchgate.net/profile/Julien-P-Irmer
        text: <i class="fa-solid fa-flask"></i>
      - href: https://orcid.org/0000-0002-7544-6483
        text: "<img src='/assets/orcid.webp' alt='ORCID' style='height:1.2em;'>"      
      - href: https://pandar.netlify.app/authors/julien-p.-irmer/
        text: <i class="fa-solid fa-code"></i>
      - href: https://www.psychology.hu-berlin.de/de/mitarbeiter/1696000
        text: <i class="fa-solid fa-graduation-cap"></i>

  page-footer:
    left: |
      <span class="faux-block"><i class="fa-brands fa-creative-commons"></i> 2025 Julien P. Irmer, </span>
      <span class="faux-block">Built with <a href="https://quarto.org/">Quarto</a></span>
    center: |
      <span class="faux-block"><a href="https://github.com/jpirmer/julien.irmer.github.io"><i class="fa-brands fa-github"></i> Source Code</a></span>
    right:
      - text: "Impressum"
        href: impressum/impressum.qmd

format:
  html:
    include-in-header: assets/head.html
    css: styles.css
    toc: true

bibliography: Articles.bib
csl: apa.csl