project:
  type: website
  output-dir: docs  

website:
  title: "Dr. Julien P. Irmer"
  navbar:
    logo: assets/me.png
    left:
      - index.qmd 
      - publications.qmd
      - talks.qmd
      - workshops.qmd
      - cv.qmd
      - current.qmd
    right:
      - href: "https://scholar.google.com/citations?user=s7I2mOAAAAAJ&hl=en&oi=sra"
        text: "<i class='ai ai-google-scholar' aria-label='Google Scholar' title='Google Scholar'></i>"
      - href: "https://www.researchgate.net/profile/Julien-P-Irmer"
        text: "<i class='ai ai-researchgate' aria-label='ResearchGate' title='ResearchGate'></i>"
      - href: "https://orcid.org/0000-0002-7544-6483"
        text: "<i class='ai ai-orcid' aria-label='ORCID' title='ORCID'></i>"
      - href: "https://osf.io/9hnkp/"
        text: "<i class='ai ai-osf' aria-label='OSF' title='OSF'></i>"
      - href: "https://github.com/jpirmer"
        text: "<i class='fa-brands fa-github' aria-label='GitHub' title='GitHub'></i>"
      - href: "https://www.linkedin.com/in/jpirmer"
        text: "<i class='fa-brands fa-linkedin' aria-label='LinkedIn' title='LinkedIn'></i>"
      - href: "https://pandar.netlify.app/authors/julien-p.-irmer/"
        text: "<i class='fa-solid fa-code' aria-label='PandaR' title='PandaR'></i>"
      - href: "https://www.psychology.hu-berlin.de/de/mitarbeiter/1696000"
        text: "<i class='fa-solid fa-graduation-cap' aria-label='HU Berlin' title='HU Berlin'></i>"

  page-footer:
    left: |
      <span class="faux-block"><i class="fa-brands fa-creative-commons"></i> 2025 Julien P. Irmer, </span>
      <span class="faux-block">Built with <a href="https://quarto.org/">Quarto</a></span>
    center: |
      <span class="faux-block">
        <a href="https://github.com/jpirmer/jpirmer.github.io">
          <i class="fa-brands fa-github"></i> Source Code
        </a>
      </span><br>
      <span class="last-updated">Last updated: <span id="last-upd"></span></span>
      <script>
        (function(){
          var d = new Date(document.lastModified);
          var opts = {year:'numeric', month:'long', day:'numeric'};
          document.getElementById('last-upd').textContent = d.toLocaleDateString('en-US', opts);
        })();
      </script>
    right:
      - text: "Impressum"
        href: impressum/impressum.qmd

format:
  html:
    include-in-header: assets/head.html
    css: styles.css
    toc: true

bibliography: Articles.bib
csl: apa.csl